apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komoplane-app
  namespace: argocd-system
spec:
  project: default
  source:
    repoURL: https://helm-charts.komodor.io
    chart: komoplane
    targetRevision: 0.1.6
    helm:
      releaseName: komoplane
  destination:
    server: https://kubernetes.default.svc
    namespace: komoplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
