apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xqueues.platform.hooli.tech
spec:
  group: platform.hooli.tech
  names:
    kind: XQueue
    plural: xqueues
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                location:
                  type: string
                  oneOf:
                    - pattern: "^EU$"
                    - pattern: "^US$"
                tags:
                  type: object
                  additionalProperties:
                    type: string
                visibilityTimeoutSeconds:
                  type: integer
                  minimum: 0
                maxMessageSize:
                  type: integer
                  minimum: 1024
                providerName:
                  type: string
              required:
                - location
                - providerName
      served: true
      referenceable: true
  claimNames:
    kind: XQueueClaim
    plural: xqueuesclaim
