apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-app
  namespace: argocd-system
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: 3.4.0
    helm:
      releaseName: kyverno
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
