apiVersion: platform.hooli.tech/v1alpha1
kind: XQueueClaim
metadata:
  name: platform-rocks
spec:
  location: US
  providerName: default
  visibilityTimeoutSeconds: 30
  maxMessageSize: 262144
  tags:
    cost: lorem-ipsum
