name: Validate Crossplane Claims

on:
  pull_request:
    paths:
      - "crossplane/claims/**/*.yaml"
      - "crossplane/claims/**/*.yml"
      - "kyverno/**/*.yaml"
      - "kyverno/**/*.yml"

jobs:
  validate-claims:
    name: Validate Claims YAML with Kyverno
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Kyverno CLI
        run: |
          curl -LO https://github.com/kyverno/kyverno/releases/download/v1.12.0/kyverno-cli_v1.12.0_linux_x86_64.tar.gz
          tar -xvf kyverno-cli_v1.12.0_linux_x86_64.tar.gz
          sudo mv kyverno /usr/local/bin/
          kyverno version

      - name: Run Kyverno policy checks on claims
        run: |
          kyverno apply ./kyverno --resource ./crossplane/claims
